//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazaki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordonnees
    {
        public int id { get; set; }
        public string Ville { get; set; }
        public string Adresse { get; set; }
        public string Sexe { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
    
        public virtual Formateurs Formateur { get; set; }
        public virtual Operateurs Operateur { get; set; }
    }
}
