//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazaki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordonnees
    {
        public int id { get; set; }
        public string Ville { get; set; }
        public string Adresse { get; set; }
        public string Sexe { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public Nullable<int> postalCode { get; set; }
        public string civilStatus { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string jobTitle { get; set; }
        public string educationLevel { get; set; }
        public Nullable<System.DateTime> graduationDate { get; set; }
        public Nullable<System.DateTime> dateOfEmployment { get; set; }
        public string departementName { get; set; }
        public Nullable<System.DateTime> dateOfStartingWorkInDep { get; set; }
    
        public virtual Operateurs Operateur { get; set; }
    }
}
