//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazaki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int Id { get; set; }
        public string type { get; set; }
        public Nullable<double> resultat { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> id_op { get; set; }
        public Nullable<int> id_form { get; set; }
    
        public virtual Formateur Formateur { get; set; }
        public virtual Operateur Operateur { get; set; }
    }
}
