//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazaki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int Id { get; set; }
        public string type { get; set; }
        public double resultat { get; set; }
        public System.DateTime date { get; set; }
        public int id_op { get; set; }
        public int id_form { get; set; }
        public string niveau { get; set; }
        public string nom_test { get; set; }
        public bool passed { get; set; }
    
        public virtual Formateurs Formateur { get; set; }
        public virtual Operateurs Operateur { get; set; }
    }
}
